all:
  hosts:
    web1:
      ansible_host: 192.168.82.133
      ansible_user: david
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_private_key_file: "/home/david/Escritorio/prueba ansible/id_rsa_deploy"